### ISSUE TITLE
the profile system don't seem to work

### ISSUE THREAD

**Issue by meandred** [DrBranestawm/BCAR#81]
I have tried many times but it feels like the profile system just clones each other

**Comment by meandred** [comment]
to further say what I mean, when I have saved a profile as profile 1, trying to set a new tail and ears and wings as profile 2 saves as profile 1 even though I go through the menu for saving as profile 2, and BCAR also recognizes I have a saved profile 2 but it thinks both are the exact same even when I load profile 1 and try to fix it it saves as both profiles

**Comment by DrBranestawm** [comment]
Should already be fixed since BCAR+ v0.7.0
