### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'pronoun')

### ISSUE THREAD

**Issue by bloodstone1476** [DrBranestawm/BCAR#91]
Uncaught (in promise)        bcarBeta.js?v=1697322898836:1284 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'pronoun')
    at migrate_gender (bcarBeta.js?v=1697322898836:1284:16)
    at bcarSettingsLoad (bcarBeta.js?v=1697322898836:1512:9)
    at async bcarBeta.js?v=1697322898836:73:3

I installed the stable version, and chrome is the latest version 118.0.5993.71, but installing bcar through Tampermonkey, bookmarks, or FUSAM has no effect, but the developer tools show the bugs in console above.

**Comment by DrBranestawm** [comment]
Pushed a fix!
